# Pretraining on Unlabeled Data

## Evaluating generative text models

### Using GPT to generate text

In [1]:
import torch
from previous_chapters import GPTModel

GPT_CONFIG_124M = {
    "vocab_size": 50257,   # Vocabulary size
    "context_length": 256, # Shortened context length (orig: 1024)
    "emb_dim": 768,        # Embedding dimension
    "n_heads": 12,         # Number of attention heads
    "n_layers": 12,        # Number of layers
    "drop_rate": 0.1,      # Dropout rate
    "qkv_bias": False      # Query-key-value bias
}

torch.manual_seed(123)
model = GPTModel(GPT_CONFIG_124M)
model.eval();

In [2]:
import tiktoken
from previous_chapters import generate_text_simple

def text_to_token_ids(text, tokenizer):
    encoded = tokenizer.encode(text, allowed_special = {"<|endoftext|>"})
    encoded_tensor = torch.tensor(encoded).unsqueeze(0)
    return encoded_tensor

def token_ids_to_text(token_ids, tokenizer):
    flat = token_ids.squeeze(0)
    return tokenizer.decode(flat.tolist())

start_context = "Every effort moves you"
tokenizer = tiktoken.get_encoding("gpt2")

token_ids = generate_text_simple(
    model = model,
    idx = text_to_token_ids(start_context, tokenizer),
    max_new_tokens = 10,
    context_size=GPT_CONFIG_124M["context_length"]
)

print("Output text:\n", token_ids_to_text(token_ids, tokenizer))

Output text:
 Every effort moves you rentingetic wasnم refres RexMeCHicular stren


## Culating the text generation loss: cross-entropy and perplexity

In [3]:
inputs = torch.tensor([[16833, 3626, 6100],   # ["every effort moves",
                       [40,    1107, 588]])   #  "I really like"]

targets = torch.tensor([[3626, 6100, 345  ],  # [" effort moves you",
                        [1107,  588, 11311]]) #  " really like chocolate"]

In [4]:
with torch.no_grad():
    logits = model(inputs)

probas = torch.softmax(logits, dim = -1)
print(probas.shape)

torch.Size([2, 3, 50257])


In [5]:
logits


tensor([[[ 0.1113, -0.1057, -0.3666,  ...,  0.2843, -0.8824,  0.1074],
         [-0.6109, -0.5167, -0.7613,  ...,  0.5450, -1.0319, -0.2175],
         [ 0.5707, -0.6459, -0.0701,  ...,  0.7419, -0.1806, -0.2217]],

        [[-0.2968,  0.1949, -0.1649,  ..., -0.4867,  0.7218, -0.1714],
         [-0.8375,  0.0612, -0.4641,  ...,  0.2327, -0.3889, -0.0770],
         [ 0.5614,  0.6919,  0.8915,  ..., -0.9472,  1.2411, -0.2056]]])

In [6]:
token_ids = torch.argmax(probas, dim=-1, keepdim=True)
print("Token IDs:\n", token_ids)

Token IDs:
 tensor([[[16657],
         [  339],
         [42826]],

        [[49906],
         [29669],
         [41751]]])


In [7]:
print(f"Targets batch 1 : {token_ids_to_text(targets[0], tokenizer)}")
print(f"Outputs batch 1 : {token_ids_to_text(token_ids[0].flatten(), tokenizer)}")

Targets batch 1 :  effort moves you
Outputs batch 1 :  Armed heNetflix


In [8]:
text_idx = 0
target_probas_1 = probas[text_idx, [0, 1, 2], targets[text_idx]]
print("Text 1:- ", target_probas_1)

text_idx = 1
target_probas_2 = probas[text_idx, [0, 1, 2], targets[text_idx]]
print("Text 2:", target_probas_2)

Text 1:-  tensor([7.4541e-05, 3.1061e-05, 1.1563e-05])
Text 2: tensor([1.0337e-05, 5.6776e-05, 4.7559e-06])


In [9]:
listi = torch.tensor([[[1,2,3,4,5],
                       [6,7,8,9,10],
                       [11,12,13,14,15]],
                      [[16,17,18,19,20],
                      [21,22,23,24,25],
                      [26,27,28,29,30]]])

In [10]:
listi.shape

torch.Size([2, 3, 5])

In [11]:
abc = torch.argmax(listi, dim =-1 , keepdim= True)
print(abc)

tensor([[[4],
         [4],
         [4]],

        [[4],
         [4],
         [4]]])


In [12]:
print(f"Targets batch 1: {token_ids_to_text(targets[0], tokenizer)}")
print(f"Outputs batch 1: {token_ids_to_text(token_ids[0].flatten(), tokenizer)}")

Targets batch 1:  effort moves you
Outputs batch 1:  Armed heNetflix


In [13]:
text_ids = 0
target_probaas_1 = probas[text_ids, [0, 1, 2], targets[text_ids]]
print("Text 1:", target_probas_1)

text_ids = 1
target_proabas_2 = probas[text_ids, [0, 1, 2], targets[text_ids]]
print("Text 2:", target_probas_2)

Text 1: tensor([7.4541e-05, 3.1061e-05, 1.1563e-05])
Text 2: tensor([1.0337e-05, 5.6776e-05, 4.7559e-06])


In [14]:
targets[text_ids]

tensor([ 1107,   588, 11311])

In [15]:
log_probas = torch.log(torch.cat((target_probas_1, target_probas_2)))
print(log_probas)
# For logarithmic functions, smaller input values (between 0 and 1) produce larger negative outputs. The closer the value is to zero, the more negative the logarithm becomes.

tensor([ -9.5042, -10.3796, -11.3677, -11.4798,  -9.7764, -12.2561])


In [16]:
-1*torch.mean(log_probas) # this is the cross entropy loss

tensor(10.7940)

In [17]:
# tensor(10.7940) we want this value to be close to zero for good response

In [18]:
logits.shape

torch.Size([2, 3, 50257])

In [19]:
logits_flat = logits.flatten(0, 1)
logits_flat.shape

torch.Size([6, 50257])

In [20]:
targets

tensor([[ 3626,  6100,   345],
        [ 1107,   588, 11311]])

In [21]:
targets.shape

torch.Size([2, 3])

In [22]:
targets_flat = targets.flatten()
targets_flat.shape

torch.Size([6])

In [23]:
targets_flat

tensor([ 3626,  6100,   345,  1107,   588, 11311])

In [24]:
torch.nn.functional.cross_entropy(logits_flat, targets_flat)

tensor(10.7940)

## 5.1.3 Calculating the training and validation set losses

In [25]:
file_path = r"D:\Aryan Work\Projects\Sebastian Raschka\GPT\data\Solar Report 24-25.txt"
with open(file_path, "r", encoding="utf-8") as file:
    text_data = file.read()
text_data

'### Power to Propel the Future\n\nSolar Industries India Limited Annual Report 2024-25\n\n### About the Report\n\nThis is Solar\'s Integrated Annual Report for FY 2024-25, providing a comprehensive assessment of financial and non-financial metrics. This report covers the financial year from April 01, 2024, to March 31, 2025 .\n\nThis Report is prepared in accordance with the International Integrated Reporting Framework published by the International Integrated Reporting Council (IIRC). We have also followed guidelines and commitments outlined in the GRI Standards, Sustainable Development Goals (SDGs), and other relevant standards and frameworks.\n\n### Forward-looking statements\n\nSome information in this report may contain forward-looking statements which include statements regarding Company\'s expected financial position and results of operations, business plans and prospects, and are generally identified by forward-looking words such as \'believe,\' \'plan,\' \'anticipate,\' \'con

In [26]:
total_characters = len(text_data)
total_tokens = len(tokenizer.encode(text_data))

print("Characters:", total_characters)
print("Tokens:", total_tokens)

Characters: 1206048
Tokens: 284788


In [27]:
from previous_chapters import create_dataloader_v1

train_ratio = 0.90
split_idx =  int(train_ratio * len(text_data))
train_data = text_data[:split_idx]
val_data = text_data[split_idx:]

torch.manual_seed(123)

train_loader = create_dataloader_v1(
    train_data,
    batch_size = 2,
    max_length = GPT_CONFIG_124M['context_length'],
    stride = GPT_CONFIG_124M['context_length'],
    drop_last = True,
    shuffle = True,
    num_workers = 0
)

val_loader = create_dataloader_v1(
    val_data,
    batch_size = 2,
    max_length = GPT_CONFIG_124M['context_length'],
    stride = GPT_CONFIG_124M['context_length'],
    drop_last = False,
    shuffle = False,
    num_workers = 0
)

In [31]:
print("Train Loader")
i = 0
for x, y in train_loader:
    print(x.shape, y.shape)
    i = i + 1
print(i)

Train Loader
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) 

In [33]:
print("Train Loader")
i = 1
for x, y in train_loader:
    print(f'X :- {x}')
    print(f'Y :- {y}')
    print(f'Batch :- {i}\n-------------------------------------------------------------------------------------------------')
    i += 1
print(i)

Train Loader
X :- tensor([[  307,   604,     4,   287, 30440, 32190,    11,   880,  2174,   262,
          5018,   286, 37270,   338,  2496,   286,   642,  7225,   198,   198,
          5886,   262,  7090,  3381,    11,  3349,   318, 11092,   276,   284,
          2811,  1088,   718,  7441,  7986,   416,  6596,  1597,  4258,    13,
         46333,   286, 12506,   389,  1884,   284,  4729,  3744,  4896,    11,
          1390,  8708,  4128, 20877,   357,    37, 17931,   737,  7123,  1370,
         10610,   318,   635,  2938,   284,  3520,  1877,   290,  8245,    13,
           198,   198, 21017, 16256,    23,   198,   198,  5497,  1952,   544,
           338,  3773,  4477,   284, 10176, 31307,    11,   351, 12396,  3349,
         13301,   379,   642,    13,    16,     4,   287, 30440, 48609,   290,
           642,    13,    17,     4,   287, 30440, 32190,    13,  7123,  1370,
         10610, 20955,   284,   352,    13,    22,     4,   287, 30440, 48609,
           290,  5928,  3512,  615

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [35]:
print("Val Loader")
i = 1
for x, y in val_loader:
    print(x.shape, y.shape)
    i+=1
print(i)

Val Loader
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) torch.Size([2, 256])
torch.Size([2, 256]) to

In [40]:
train_tokens = 0
for input_batch, target_batch in train_loader:
    train_tokens += input_batch.numel()

val_tokens = 0
for input_batch, target_batch in val_loader:
    val_tokens += input_batch.numel()

print("Training tokens:", train_tokens)
print("Validation tokens:", val_tokens)
print("All tokens:", train_tokens + val_tokens)

Training tokens: 252416
Validation tokens: 32256
All tokens: 284672


In [42]:
torch.cuda.is_available()

True

In [43]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [46]:
model.to(device);

In [56]:
def calc_loss_batch(input_batch, target_batch, model, device):
    input_batch, target_batch = input_batch.to(device), target_batch.to(device)
    logits = model(input_batch)
    loss = torch.nn.functional.cross_entropy(logits.flatten(0, 1), target_batch.flatten())
    return loss

def calc_loss_loader(data_loader, model, device, num_batches=None):
    total_loss = 0.
    if len(data_loader) == 0:
        return float("nan")
    elif num_batches is None:
        num_batches = len(data_loader)
    else:
        num_batches = min(num_batches, len(data_loader))
    for i, (input_batch, target_batch) in enumerate(data_loader):
        if i < num_batches:
            loss = calc_loss_batch(input_batch, target_batch, model, device)
            total_loss+= loss.item()
        else:
            break
    return total_loss / num_batches

In [57]:
torch.manual_seed(123) # For reproducibility due to the shuffling in the data loader

with torch.no_grad(): # Disable gradient tracking for efficiency because we are not training, yet
    train_loss = calc_loss_loader(train_loader, model, device)
    val_loss = calc_loss_loader(val_loader, model, device)

print("Training loss:", train_loss)
print("Validation loss:", val_loss)

Training loss: 10.972490858112822
Validation loss: 10.96913967435322


In [58]:
# perplexlity
torch.exp(torch.tensor([10.972490858112822]))

tensor([58249.5273])

In [ ]:
# tensor([58249.5273]) this value is the value which tell us how many tokens is not known by model

# 5.2 Training an LLM

In [64]:
def train_model_simple(model, train_loader, val_loader, optimizer, device, num_epochs,
                      eval_freq, eval_iter, start_context, tokenizer):
    train_losses, val_losses, track_tokens_seen = [], [], []
    tokens_seen, global_step = 0, -1

    # Main training loop
    for epoch in range(num_epochs):
        model.train()

        for input_batch, target_batch in train_loader:
            optimizer.zero_grad()
            loss = calc_loss_batch(input_batch, target_batch, model, device)
            loss.backward()
            optimizer.step()
            tokens_seen += input_batch.numel()
            global_step += 1

            # Eval step
            if global_step % eval_freq == 0:
                train_loss, val_loss = evaluate_model(
                    model, train_loader, val_loader, device, eval_iter)
                train_losses.append(train_loss)
                val_losses.append(val_loss)
                track_tokens_seen.append(tokens_seen)
                print(f"Ep {epoch+1} (Step {global_step:06d}):"
                     f"Train loss {train_loss:.3f}, Val loss {val_loss:.3f}")

        # Print sample text after each epoch
        generate_and_print_sample(
            model, tokenizer, device, start_context
        )
    
    return train_losses , val_losses, track_tokens_seen


def evaluate_model(model, train_loader, val_loader, device, eval_iter):
    model.eval()
    with torch.no_grad():
        train_loss = calc_loss_loader(train_loader, model, device, num_batches = eval_iter)
        val_loss = calc_loss_loader(val_loader, model, device, num_batches = eval_iter)
    model.train()
    return train_loss, val_loss

def generate_and_print_sample(model, tokenizer, device, start_context):
    model.eval()
    context_size = model.pos_emb.weight.shape[0]
    encoded = text_to_token_ids(start_context, tokenizer).to(device)
    with torch.no_grad():
        token_ids = generate_text_simple(
        model = model, idx=encode,
        max_new_tokens=50, context_size=context_size
        )
    decode_text = token_ids_to_text(token_ids, tokenizer)
    print(decode_text.replace("\n", " "))
    model.train()

In [65]:
torch.manual_seed(123)
model = GPTModel(GPT_CONFIG_124M)
model.to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=0.0004, weight_decay=0.1)

num_epochs = 10
train_losses, val_losses, tokens_seen = train_model_simple(
    model, train_loader, val_loader, optimizer, device,
    num_epochs=num_epochs, eval_freq=5, eval_iter=5,
    start_context="Shri Narendra Modi Ji", tokenizer=tokenizer
)

Ep 1 (Step 000000):Train loss 10.189, Val loss 8.664
Ep 1 (Step 000005):Train loss 8.461, Val loss 7.332
Ep 1 (Step 000010):Train loss 8.304, Val loss 6.563


KeyboardInterrupt: 